### ISSUE TITLE
autocomplete entries not showing up, when other autocompletions exist

### ISSUE THREAD

**Issue by robinrosenstock** [randy3k/UnicodeCompletion#8] opened 2017-08-25 13:05 UTC
when there are autocompletions for, say... `\allo` than the entries for `\a` are not shownig up in the autocomplete (_no_ `\alpha` and `\aleph`, are showing up).
For bypassing this, I have to use some letter as the first letter, for that no autocompletions yet exists, for example `\yno`, then (in this particular example) I would push the backspace three times (`\`) and the autocompletions are showing up again when hitting a: `\a`.

__Info: The backlash `\` is in my `word_separators` parameter inside my settings.__

I use the current Version of Sublime.

**Comment by robinrosenstock** [comment] 2017-08-25 13:18
confirmed with a fresh installation

**Comment by randy3k** [comment] 2017-08-25 17:40
It is now fixed. It was caused by the backslash autocompletion trigger of the latex syntax.

**Closed as completed** 2017-08-25 17:40 UTC
